import crypto from 'node:crypto';
import { sql } from '@/lib/pg';
import { ensureSchema } from '@/lib/schema';
import { getWhiteLabelConfig, type WhiteLabelConfig } from '@/lib/white-label';
import { logger } from '@/lib/logger';

export interface ResolvedPartnerLink {
  token: string;
  url: string;
  directUrl: string;
  refUrl: string;
  partner: {
    id: string;
    razaoSocial: string;
    nomeFantasia: string | null;
    email: string;
    phone: string | null;
    status: string;
    code: string;
    whiteLabel: WhiteLabelConfig;
  };
  linkId: string;
  productId: string | null;
}

export function getAppBaseUrl(): string {
  return process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, '') || 'https://duolife.com.br';
}

/**
 * Obtém ou cria automaticamente um link de venda pública ativo para o parceiro.
 */
export async function getOrCreatePartnerSaleLink(partnerId: string): Promise<{
  id: string;
  token: string;
  url: string;
  directUrl: string;
  refUrl: string;
  code: string;
}> {
  await ensureSchema();

  // 1. Busca se o parceiro já possui um link ativo
  const existing = await sql<
    Array<{
      id: string;
      token: string;
      partner_id: string;
      metadata: Record<string, unknown>;
    }>
  >`
    SELECT id, token, partner_id, metadata
    FROM public_sale_links
    WHERE partner_id = ${partnerId}
      AND status = 'active'
      AND (expires_at IS NULL OR expires_at > NOW())
    ORDER BY created_at DESC
    LIMIT 1
  `;

  // Busca o código do parceiro (wixCode ou slug)
  const [partnerRow] = await sql<
    Array<{
      id: string;
      metadata: Record<string, unknown>;
    }>
  >`
    SELECT id, metadata
    FROM partners
    WHERE id = ${partnerId}
    LIMIT 1
  `;

  const wl = partnerRow ? getWhiteLabelConfig(partnerRow.metadata) : null;
  const partnerCode = (wl?.wixCode || wl?.slug || partnerId).trim();
  const baseUrl = getAppBaseUrl();

  if (existing && existing.length > 0) {
    const link = existing[0];
    return {
      id: link.id,
      token: link.token,
      url: `${baseUrl}/contratar/${link.token}`,
      directUrl: `${baseUrl}/contratar/${link.token}`,
      refUrl: `${baseUrl}/?ref=${encodeURIComponent(partnerCode || link.token)}`,
      code: partnerCode,
    };
  }

  // 2. Se não existir, gera um token novo
  const token = `dlk_${crypto.randomBytes(18).toString('base64url')}`;
  const [created] = await sql<
    Array<{
      id: string;
      token: string;
    }>
  >`
    INSERT INTO public_sale_links (
      token,
      partner_id,
      flow_type,
      label,
      status,
      metadata
    )
    VALUES (
      ${token},
      ${partnerId},
      'external',
      'Link Oficial de Vendas',
      'active',
      ${JSON.stringify({ autoGenerated: true })}::jsonb
    )
    RETURNING id, token
  `;

  logger.info({ partnerId, token: created.token }, 'partner.autoSaleLink.created');

  return {
    id: created.id,
    token: created.token,
    url: `${baseUrl}/contratar/${created.token}`,
    directUrl: `${baseUrl}/contratar/${created.token}`,
    refUrl: `${baseUrl}/?ref=${encodeURIComponent(partnerCode || created.token)}`,
    code: partnerCode,
  };
}

/**
 * Resolve unificadamente qualquer um dos três formatos:
 * 1. [token] (ex: 'dlk_ABC123...')
 * 2. ?ref=[token]
 * 3. ?ref=ABC (onde ABC é wixCode, slug ou ID do parceiro)
 */
export async function resolvePartnerOrLink(refOrToken: string): Promise<ResolvedPartnerLink | null> {
  if (!refOrToken || typeof refOrToken !== 'string') return null;
  const query = refOrToken.trim();
  if (!query) return null;

  await ensureSchema();
  const baseUrl = getAppBaseUrl();

  // 1ª Tentativa: Match exato por token da tabela public_sale_links
  const linkMatches = await sql<
    Array<{
      link_id: string;
      token: string;
      product_id: string | null;
      partner_id: string;
      razao_social: string;
      nome_fantasia: string | null;
      email: string;
      phone: string | null;
      status: string;
      partner_metadata: Record<string, unknown>;
    }>
  >`
    SELECT
      pl.id AS link_id,
      pl.token,
      pl.product_id,
      p.id AS partner_id,
      p.razao_social,
      p.nome_fantasia,
      p.email,
      p.phone,
      p.status,
      p.metadata AS partner_metadata
    FROM public_sale_links pl
    JOIN partners p ON p.id = pl.partner_id
    WHERE pl.token = ${query}
      AND pl.status = 'active'
      AND (pl.expires_at IS NULL OR pl.expires_at > NOW())
    LIMIT 1
  `;

  if (linkMatches && linkMatches.length > 0) {
    const item = linkMatches[0];
    const wl = getWhiteLabelConfig(item.partner_metadata);
    const code = wl.wixCode || wl.slug || item.token;

    return {
      token: item.token,
      url: `${baseUrl}/contratar/${item.token}`,
      directUrl: `${baseUrl}/contratar/${item.token}`,
      refUrl: `${baseUrl}/?ref=${encodeURIComponent(code)}`,
      partner: {
        id: item.partner_id,
        razaoSocial: item.razao_social,
        nomeFantasia: item.nome_fantasia,
        email: item.email,
        phone: item.phone,
        status: item.status,
        code,
        whiteLabel: wl,
      },
      linkId: item.link_id,
      productId: item.product_id,
    };
  }

  // 2ª Tentativa: Match por código do parceiro (wixCode / slug / id)
  const partnerMatches = await sql<
    Array<{
      id: string;
      razao_social: string;
      nome_fantasia: string | null;
      email: string;
      phone: string | null;
      status: string;
      metadata: Record<string, unknown>;
    }>
  >`
    SELECT
      id,
      razao_social,
      nome_fantasia,
      email,
      phone,
      status,
      metadata
    FROM partners
    WHERE (
      metadata->'whiteLabel'->>'wixCode' ILIKE ${query}
      OR metadata->'whiteLabel'->>'slug' ILIKE ${query}
      OR id = ${query}
    )
    AND status != 'suspended'
    LIMIT 1
  `;

  if (partnerMatches && partnerMatches.length > 0) {
    const partner = partnerMatches[0];
    const wl = getWhiteLabelConfig(partner.metadata);
    const code = wl.wixCode || wl.slug || partner.id;

    // Obtém ou cria o link de contratação deste parceiro
    const partnerLink = await getOrCreatePartnerSaleLink(partner.id);

    return {
      token: partnerLink.token,
      url: `${baseUrl}/contratar/${partnerLink.token}`,
      directUrl: `${baseUrl}/contratar/${partnerLink.token}`,
      refUrl: `${baseUrl}/?ref=${encodeURIComponent(code)}`,
      partner: {
        id: partner.id,
        razaoSocial: partner.razao_social,
        nomeFantasia: partner.nome_fantasia,
        email: partner.email,
        phone: partner.phone,
        status: partner.status,
        code,
        whiteLabel: wl,
      },
      linkId: partnerLink.id,
      productId: null,
    };
  }

  return null;
}
