import { RamoConfig } from '../types';

/**
 * Configuração declarativa do Seguro D&O (Directors & Officers) -
 * Responsabilidade Civil de Administradores, Conselheiros e Diretores Executivos.
 */
export const doExecutivosConfig: RamoConfig = {
  ramoId: 'do-executivos',
  name: 'Seguro D&O Administradores, Conselheiros & Executivos',
  shortName: 'D&O Executivos',
  category: 'diretores_administradores',
  flowKeys: ['do_executivos_v1', 'do_corporate_v1'],
  pricingStrategy: 'do_executivos_planos_v1',
  policyPrefix: 'DL-DO',
  targetAudience: 'Sociedades limitadas, anônimas (capital aberto ou fechado), cooperativas e holdings para proteção patrimonial de seus gestores e administradores.',

  // D&O não possui conselho de classe profissional de pessoa física, pois a tomadora é uma Pessoa Jurídica
  registroProfissional: undefined,

  additionalFields: [
    {
      key: 'razaoSocialTomadora',
      label: 'Razão Social da Tomadora',
      type: 'text',
      placeholder: 'Razão social completa da empresa tomadora',
      required: true,
      helpText: 'Pessoa jurídica contratante do seguro em benefício de seus administradores segurados.',
    },
    {
      key: 'cnpjTomadora',
      label: 'CNPJ da Sociedade Tomadora',
      type: 'cpf_cnpj',
      placeholder: '00.000.000/0000-00',
      required: true,
      helpText: 'CNPJ ativo da matriz da empresa tomadora.',
    },
    {
      key: 'ativoTotal',
      label: 'Ativo Total da Sociedade',
      type: 'currency',
      placeholder: 'R$ 0,00',
      required: true,
      helpText: 'Valor contábil do Ativo Total constante no último balanço patrimonial encerrado.',
    },
    {
      key: 'faturamentoAnual',
      label: 'Receita Operacional Bruta Anual',
      type: 'currency',
      placeholder: 'R$ 0,00',
      required: true,
      helpText: 'Faturamento bruto acumulado dos últimos 12 meses da sociedade e suas controladas.',
    },
  ],

  especialidadesLabel: 'Setor Econômico de Atuação da Sociedade',
  especialidades: [
    { key: 'tecnologiaSoftware', label: 'Tecnologia, Software & Plataformas Digitais', description: 'Empresas de SaaS, software, telecom e TI' },
    { key: 'industriaManufatura', label: 'Indústria, Manufatura & Bens de Consumo', description: 'Plantas industriais, transformação e bens duráveis' },
    { key: 'comercioVarejoAtacado', label: 'Comércio Varejista & Atacadista', description: 'Varejo físico, e-commerce e cadeias de distribuição' },
    { key: 'servicosFinanceirosFintech', label: 'Serviços Financeiros, Fintechs & Meios de Pagamento', description: 'Instituições de pagamento, crédito e gestão de recursos' },
    { key: 'saudeHospitaisFarma', label: 'Saúde, Hospitais & Indústria Farmacêutica', description: 'Redes hospitalares, laboratórios e farmacêuticas' },
    { key: 'construcaoImobiliario', label: 'Construção Civil, Incorporação & Real Estate', description: 'Incorporadoras imobiliárias e construtoras' },
    { key: 'agronegocio', label: 'Agronegócio & Comercialização de Commodities', description: 'Produção agrícola, insumos e agroindústria' },
    { key: 'energiaInfraestrutura', label: 'Energia, Infraestrutura & Logística', description: 'Geração/distribuição de energia, concessões e operadores logísticos' },
    { key: 'servicosGerais', label: 'Serviços Corporativos Especializados', description: 'Consultorias, engenharia consultiva e serviços terceirizados' },
    { key: 'outrosSetores', label: 'Outros Segmentos Empresariais', description: 'Demais ramos econômicos não especificados' },
  ],

  faturamentoLabel: 'Faturamento Anual Consolidado da Sociedade Tomadora',
  hasFaturamento: true,
  hasPpe: true,
  requiresUnderwriting: true,

  questionarioRisco: [
    {
      id: 'propostaRecusada',
      question: 'A sociedade tomadora, suas subsidiárias ou qualquer de seus administradores já tiveram seguro D&O recusado, agravado ou cancelado por qualquer seguradora?',
      detailKey: 'propostaDetalhe',
      detailLabel: 'Informe a seguradora, motivos do cancelamento/recusa e datas',
      requiredOnAffirmative: true,
    },
    {
      id: 'investigacaoOrgaosReguladores',
      question: 'A empresa ou qualquer executivo já foram alvo de investigações formais, inquéritos ou processos perante a CVM, BACEN, SUSEP, CADE, Ministério Público ou Polícia Federal?',
      detailKey: 'investigacaoOrgaosReguladoresDetalhe',
      detailLabel: 'Informe o órgão fiscalizador, número do inquérito, partes e situação do procedimento',
      requiredOnAffirmative: true,
    },
    {
      id: 'autuacoesFiscaisGraves',
      question: 'A tomadora possui autuações fiscais relevantes, execuções tributárias expressivas ou controvérsias com o Fisco que possam ensejar redirecionamento e responsabilização pessoal de sócios/diretores?',
      detailKey: 'autuacoesFiscaisGravesDetalhe',
      detailLabel: 'Descreva os montantes tributários envolvidos, garantias ofertadas e riscos de redirecionamento patrimonial',
      requiredOnAffirmative: true,
    },
    {
      id: 'disputasSocietarias',
      question: 'Nos últimos 5 anos, houve litígios entre acionistas/quotistas, ação de dissolução societária, pedidos de falência, recuperação judicial ou intervenção na sociedade?',
      detailKey: 'disputasSocietariasDetalhe',
      detailLabel: 'Detalhe a disputa entre sócios, processos em curso e reflexos na governança',
      requiredOnAffirmative: true,
    },
    {
      id: 'reclamacoesTrabalhistasDiretoria',
      question: 'A sociedade tomadora ou seus gestores respondem a ações civis públicas, inquéritos civis trabalhistas (MPT) ou reclamações individuais envolvendo assédio moral/sexual ou dano coletivo direcionado à diretoria?',
      detailKey: 'reclamacoesTrabalhistasDiretoriaDetalhe',
      detailLabel: 'Informe as reclamações trabalhistas graves, órgãos envolvidos e fase de julgamento',
      requiredOnAffirmative: true,
    },
    {
      id: 'circunstanciasConhecidasDo',
      question: 'Existe conhecimento atual de qualquer fato, ato, omissão, quebra de dever fiduciário ou controvérsia que possa razoavelmente resultar em reclamação futura coberta pela apólice D&O?',
      detailKey: 'circunstanciasConhecidasDoDetalhe',
      detailLabel: 'Descreva detalhadamente a situação conhecida e partes envolvidas',
      requiredOnAffirmative: true,
    },
  ],

  planos: [
    {
      tipoDePlano: '1M',
      nomeExibido: 'Plano 1 Milhão',
      cobertura: 'R$ 1.000.000,00',
      franquia: 'Isento para PF (R$ 0,00) / R$ 20.000,00 para PJ',
      ordem: 1,
      parcela: 'R$ 7.500,00',
      parcela2X: 'R$ 3.750,00',
      parcela3X: 'R$ 2.500,00',
      parcela4X: 'R$ 1.875,00',
      parcela5X: 'R$ 1.500,00',
      parcela6X: 'R$ 1.250,00',
      valorPagoKovr: 4900,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '2M',
      nomeExibido: 'Plano 2 Milhões',
      cobertura: 'R$ 2.000.000,00',
      franquia: 'Isento para PF (R$ 0,00) / R$ 35.000,00 para PJ',
      ordem: 2,
      parcela: 'R$ 13.200,00',
      parcela2X: 'R$ 6.600,00',
      parcela3X: 'R$ 4.400,00',
      parcela4X: 'R$ 3.300,00',
      parcela5X: 'R$ 2.640,00',
      parcela6X: 'R$ 2.200,00',
      valorPagoKovr: 8600,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '5M',
      nomeExibido: 'Plano 5 Milhões',
      cobertura: 'R$ 5.000.000,00',
      franquia: 'Isento para PF (R$ 0,00) / R$ 50.000,00 para PJ',
      ordem: 3,
      parcela: 'R$ 27.500,00',
      parcela2X: 'R$ 13.750,00',
      parcela3X: 'R$ 9.166,67',
      parcela4X: 'R$ 6.875,00',
      parcela5X: 'R$ 5.500,00',
      parcela6X: 'R$ 4.583,33',
      valorPagoKovr: 17900,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '10M',
      nomeExibido: 'Plano 10 Milhões',
      cobertura: 'R$ 10.000.000,00',
      franquia: 'Isento para PF (R$ 0,00) / R$ 100.000,00 para PJ',
      ordem: 4,
      parcela: 'R$ 49.000,00',
      parcela2X: 'R$ 24.500,00',
      parcela3X: 'R$ 16.333,33',
      parcela4X: 'R$ 12.250,00',
      parcela5X: 'R$ 9.800,00',
      parcela6X: 'R$ 8.166,67',
      valorPagoKovr: 31800,
      maxParcelas: 6,
    },
  ],

  templateZapSignKey: 'do_executivos_contrato_v1',
};
