import { RamoConfig } from '../types';

/**
 * Configuração declarativa do Seguro de Responsabilidade Civil Profissional para
 * Contadores, Auditores Independentes e Escritórios de Contabilidade.
 */
export const rcContadoresConfig: RamoConfig = {
  ramoId: 'rc-contadores',
  name: 'RC Contadores, Auditores & Escritórios Contábeis',
  shortName: 'RC Contadores',
  category: 'responsabilidade_civil',
  flowKeys: ['rc_contabilidade_v1'],
  pricingStrategy: 'rc_contabilidade_planos_v1',
  policyPrefix: 'DL-RC-CNT',
  targetAudience: 'Contadores autônomos, peritos contábeis, auditores e sociedades de contabilidade com registro ativo no CRC.',

  registroProfissional: {
    key: 'crc',
    label: 'Registro no CRC',
    placeholder: 'Ex: 1SP123456/O-0',
    ufKey: 'crcUf',
    required: true,
    hasRqe: false,
  },

  especialidadesLabel: 'Áreas de Atuação e Serviços Contábeis',
  especialidades: [
    { key: 'fiscalTributario', label: 'Escrita Fiscal & Planejamento Tributário', description: 'Apuração de tributos diretos e indiretos, DCTF, EFD-Contribuições e SPED Fiscal' },
    { key: 'folhaPagamentoTrabalhista', label: 'Folha de Pagamento & Rotinas Trabalhistas', description: 'Processamento de folha, rescisões, encargos sociais e transmissão do eSocial' },
    { key: 'contabilidadeGeral', label: 'Contabilidade Societária & Demonstrações Financeiras', description: 'Balanço patrimonial, DRE, notas explicativas e conformidade IFRS/CPC' },
    { key: 'auditoriaIndependente', label: 'Auditoria Independente (CVM / CFC / BACEN)', description: 'Auditoria de demonstrações contábeis de companhias abertas e fechadas' },
    { key: 'periciaContabil', label: 'Perícia Contábil & Assistência Técnica Judicial', description: 'Laudos periciais contábeis em juízo e perícia arbitral' },
    { key: 'bpoFinanceiro', label: 'BPO Financeiro e Controladoria', description: 'Gestão de contas a pagar/receber, conciliação e fluxo de caixa de clientes' },
    { key: 'legalizacaoSocietaria', label: 'Abertura, Alteração e Encerramento Societário', description: 'Atos na Junta Comercial, Receita Federal e licenças municipais/estaduais' },
    { key: 'outrosContabil', label: 'Outras Atividades Contábeis Especializadas', description: 'Demais áreas de prática profissional contábil' },
  ],

  faturamentoLabel: 'Faturamento Bruto Anual de Honorários Contábeis',
  hasFaturamento: true,
  hasPpe: true,
  requiresUnderwriting: true,

  questionarioRisco: [
    {
      id: 'propostaRecusada',
      question: 'Já teve proposta de seguro de responsabilidade civil profissional contábil recusada, cancelada ou com agravo?',
      detailKey: 'propostaDetalhe',
      detailLabel: 'Informe a seguradora, época e motivo da recusa',
      requiredOnAffirmative: true,
    },
    {
      id: 'autuacaoFiscal',
      question: 'Algum cliente sofreu auto de infração, glosa de créditos tributários ou penalidade fiscal imputada a erro de apuração ou omissão do seu escritório?',
      detailKey: 'autuacaoFiscalDetalhe',
      detailLabel: 'Informe os tributos envolvidos, montante do auto de infração e estágio da discussão administrativa/judicial',
      requiredOnAffirmative: true,
    },
    {
      id: 'perdaPrazosSped',
      question: 'Nos últimos 3 anos, o escritório incorreu em perda de prazos na transmissão de obrigações acessórias (SPED, ECD, ECF, DCTF, EFD-Reinf ou eSocial) gerando multas relevantes?',
      detailKey: 'perdaPrazosSpedDetalhe',
      detailLabel: 'Informe as obrigações acessórias em atraso, valores de penalidades e ressarcimento efetuado',
      requiredOnAffirmative: true,
    },
    {
      id: 'processoCrc',
      question: 'Responde ou já respondeu a processo disciplinar, ético ou fiscalizatório no Conselho Regional de Contabilidade (CRC) ou CFC?',
      detailKey: 'processoCrcDetalhe',
      detailLabel: 'Informe o número do processo ético no CRC e estágio atual do procedimento',
      requiredOnAffirmative: true,
    },
    {
      id: 'reclamacaoContabil',
      question: 'Já recebeu notificação extrajudicial ou responde a ação de indenização cível ajuizada por cliente alegando erro em cálculo fiscal ou departamento pessoal nos últimos 5 anos?',
      detailKey: 'reclamacaoContabilDetalhe',
      detailLabel: 'Descreva a notificação ou ação, partes litigantes e valores reivindicados',
      requiredOnAffirmative: true,
    },
    {
      id: 'ressarcimentoCliente',
      question: 'Já efetuou ressarcimento de encargos, juros moratórios ou multas a clientes com recursos próprios do escritório nos últimos 5 anos?',
      detailKey: 'ressarcimentoClienteDetalhe',
      detailLabel: 'Informe montantes financeiros reembolsados e motivos do pagamento',
      requiredOnAffirmative: true,
    },
  ],

  planos: [
    {
      tipoDePlano: '100k',
      nomeExibido: 'Plano 100 Mil',
      cobertura: 'R$ 100.000,00',
      franquia: 'R$ 1.000,00',
      ordem: 1,
      parcela: 'R$ 720,00',
      parcela2X: 'R$ 360,00',
      parcela3X: 'R$ 240,00',
      parcela4X: 'R$ 180,00',
      parcela5X: 'R$ 144,00',
      parcela6X: 'R$ 120,00',
      valorPagoKovr: 480,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '200k',
      nomeExibido: 'Plano 200 Mil',
      cobertura: 'R$ 200.000,00',
      franquia: 'R$ 2.000,00',
      ordem: 2,
      parcela: 'R$ 1.280,00',
      parcela2X: 'R$ 640,00',
      parcela3X: 'R$ 426,67',
      parcela4X: 'R$ 320,00',
      parcela5X: 'R$ 256,00',
      parcela6X: 'R$ 213,33',
      valorPagoKovr: 850,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '500k',
      nomeExibido: 'Plano 500 Mil',
      cobertura: 'R$ 500.000,00',
      franquia: 'R$ 4.500,00',
      ordem: 3,
      parcela: 'R$ 2.580,00',
      parcela2X: 'R$ 1.290,00',
      parcela3X: 'R$ 860,00',
      parcela4X: 'R$ 645,00',
      parcela5X: 'R$ 516,00',
      parcela6X: 'R$ 430,00',
      valorPagoKovr: 1700,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '1M',
      nomeExibido: 'Plano 1 Milhão',
      cobertura: 'R$ 1.000.000,00',
      franquia: 'R$ 8.000,00',
      ordem: 4,
      parcela: 'R$ 4.350,00',
      parcela2X: 'R$ 2.175,00',
      parcela3X: 'R$ 1.450,00',
      parcela4X: 'R$ 1.087,50',
      parcela5X: 'R$ 870,00',
      parcela6X: 'R$ 725,00',
      valorPagoKovr: 2800,
      maxParcelas: 6,
    },
  ],

  templateZapSignKey: 'rc_contabilidade_contrato_v1',
};
