import { RamoConfig } from '../types';

/**
 * Configuração declarativa do Seguro de Responsabilidade Civil Profissional para
 * Engenheiros, Arquitetos, Urbanistas e Empresas de Projetos Técnicos.
 */
export const rcEngenheirosConfig: RamoConfig = {
  ramoId: 'rc-engenheiros',
  name: 'RC Engenheiros, Arquitetos & Empresas de Engenharia',
  shortName: 'RC Engenharia',
  category: 'responsabilidade_civil',
  flowKeys: ['rc_engenharia_v1'],
  pricingStrategy: 'rc_engenharia_planos_v1',
  policyPrefix: 'DL-RC-ENG',
  targetAudience: 'Engenheiros autônomos, arquitetos, projetistas e escritórios de cálculo e projetos com CREA ou CAU ativo.',

  registroProfissional: {
    key: 'creaCau',
    label: 'Inscrição CREA ou CAU',
    placeholder: 'Ex: 123456/D-SP ou CAU A12345-6',
    ufKey: 'creaCauUf',
    required: true,
    hasRqe: false,
  },

  especialidadesLabel: 'Modalidades de Engenharia e Arquitetura',
  especialidades: [
    { key: 'civilEdificacoes', label: 'Engenharia Civil / Edificações', description: 'Construção civil residencial, comercial e industrial' },
    { key: 'estruturalCalculo', label: 'Engenharia Estrutural / Cálculo de Concreto e Metálicas', description: 'Projetos e memoriais de cálculo de estruturas e fundações' },
    { key: 'eletrica', label: 'Engenharia Elétrica & Automação', description: 'Projetos elétricos de baixa/média/alta tensão e subestações' },
    { key: 'mecanica', label: 'Engenharia Mecânica & Climatização (PMOC)', description: 'Projetos de sistemas mecânicos, máquinas, elevadores e AVAC' },
    { key: 'geotecnicaFundacoes', label: 'Geotécnica / Solos / Contenções e Fundações', description: 'Estudos geotécnicos, sondagens e contenção de taludes' },
    { key: 'arquiteturaUrbanismo', label: 'Arquitetura e Urbanismo / Design de Interiores', description: 'Projetos arquitetônicos, urbanísticos e paisagísticos' },
    { key: 'segurancaTrabalho', label: 'Engenharia de Segurança do Trabalho / Laudos', description: 'PGR, LTCAT, laudos periciais e prevenção contra incêndio (AVCB)' },
    { key: 'saneamentoAmbiental', label: 'Engenharia Ambiental & Sanitária', description: 'Licenciamento ambiental, tratamento de efluentes e drenagem' },
    { key: 'outrosEng', label: 'Outras Especialidades da Engenharia', description: 'Demais modalidades regulamentadas pelo CONFEA/CAU' },
  ],

  faturamentoLabel: 'Faturamento Bruto Anual de Projetos e Contratos de Obra',
  hasFaturamento: true,
  hasPpe: true,
  requiresUnderwriting: true,

  questionarioRisco: [
    {
      id: 'propostaRecusada',
      question: 'Já teve proposta de seguro de RC Profissional ou Riscos de Engenharia recusada, cancelada ou sofrido agravo?',
      detailKey: 'propostaDetalhe',
      detailLabel: 'Informe a seguradora, época e motivo da recusa',
      requiredOnAffirmative: true,
    },
    {
      id: 'sinistroEstrutural',
      question: 'Já atuou como responsável técnico por projeto ou obra que tenha sofrido colapso total/parcial, recalque grave de fundação ou trincas estruturais severas?',
      detailKey: 'sinistroEstruturalDetalhe',
      detailLabel: 'Descreva a obra, tipo de sinistro estrutural, laudos periciais e resolução jurídica',
      requiredOnAffirmative: true,
    },
    {
      id: 'processoCreaCau',
      question: 'Já respondeu ou responde a processo ético-disciplinar, representação técnica ou sindicância no CREA, CONFEA ou CAU?',
      detailKey: 'processoCreaCauDetalhe',
      detailLabel: 'Informe a regional do conselho, número do processo ético e decisão proferida',
      requiredOnAffirmative: true,
    },
    {
      id: 'acoesJudiciaisEng',
      question: 'Já foi réu em ação judicial de reparação civil por suposto vício redibitório construtivo, erro de cálculo de ART/RRT ou atraso de entrega de obra?',
      detailKey: 'acoesJudiciaisEngDetalhe',
      detailLabel: 'Descreva o processo cível, partes, valores pleiteados e fase atual',
      requiredOnAffirmative: true,
    },
    {
      id: 'danosLindeiros',
      question: 'Nos últimos 5 anos, houve registro de danos a imóveis vizinhos/lindeiros, desabamento ou interdição pela Defesa Civil em obras sob sua responsabilidade técnica?',
      detailKey: 'danosLindeirosDetalhe',
      detailLabel: 'Descreva os danos causados, laudos técnicos e medidas indenizatórias adotadas',
      requiredOnAffirmative: true,
    },
    {
      id: 'pagouIndenizacaoEng',
      question: 'Já realizou pagamentos de indenização, refazimento de projetos ou obras às próprias expensas por falha técnica nos últimos 5 anos?',
      detailKey: 'pagouIndenizacaoEngDetalhe',
      detailLabel: 'Informe montantes financeiros pagos e termos de acordo extrajudicial',
      requiredOnAffirmative: true,
    },
  ],

  planos: [
    {
      tipoDePlano: '200k',
      nomeExibido: 'Plano 200 Mil',
      cobertura: 'R$ 200.000,00',
      franquia: 'R$ 3.000,00',
      ordem: 1,
      parcela: 'R$ 1.950,00',
      parcela2X: 'R$ 975,00',
      parcela3X: 'R$ 650,00',
      parcela4X: 'R$ 487,50',
      parcela5X: 'R$ 390,00',
      parcela6X: 'R$ 325,00',
      valorPagoKovr: 1250,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '500k',
      nomeExibido: 'Plano 500 Mil',
      cobertura: 'R$ 500.000,00',
      franquia: 'R$ 6.000,00',
      ordem: 2,
      parcela: 'R$ 3.650,00',
      parcela2X: 'R$ 1.825,00',
      parcela3X: 'R$ 1.216,67',
      parcela4X: 'R$ 912,50',
      parcela5X: 'R$ 730,00',
      parcela6X: 'R$ 608,33',
      valorPagoKovr: 2350,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '1M',
      nomeExibido: 'Plano 1 Milhão',
      cobertura: 'R$ 1.000.000,00',
      franquia: 'R$ 10.000,00',
      ordem: 3,
      parcela: 'R$ 6.100,00',
      parcela2X: 'R$ 3.050,00',
      parcela3X: 'R$ 2.033,33',
      parcela4X: 'R$ 1.525,00',
      parcela5X: 'R$ 1.220,00',
      parcela6X: 'R$ 1.016,67',
      valorPagoKovr: 3900,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '2M',
      nomeExibido: 'Plano 2 Milhões',
      cobertura: 'R$ 2.000.000,00',
      franquia: 'R$ 18.000,00',
      ordem: 4,
      parcela: 'R$ 9.900,00',
      parcela2X: 'R$ 4.950,00',
      parcela3X: 'R$ 3.300,00',
      parcela4X: 'R$ 2.475,00',
      parcela5X: 'R$ 1.980,00',
      parcela6X: 'R$ 1.650,00',
      valorPagoKovr: 6300,
      maxParcelas: 6,
    },
  ],

  templateZapSignKey: 'rc_engenharia_contrato_v1',
};
