import { RamoConfig } from '../types';

/**
 * Configuração declarativa do Seguro de Responsabilidade Civil Profissional para
 * Médicos, Clínicas e Profissionais da Medicina.
 */
export const rcMedicosConfig: RamoConfig = {
  ramoId: 'rc-medicos',
  name: 'RC Médicos, Clínicas & Serviços Médicos',
  shortName: 'RC Médicos',
  category: 'responsabilidade_civil',
  flowKeys: ['rc_medicos_v1'],
  pricingStrategy: 'rc_medicos_planos_v1',
  policyPrefix: 'DL-RC-MED',
  targetAudience: 'Médicos pessoa física, plantonistas, cirurgiões, consultórios e clínicas médicas com CRM ativo.',

  registroProfissional: {
    key: 'crm',
    label: 'Inscrição CRM',
    placeholder: 'Ex: 123456',
    ufKey: 'crmUf',
    required: true,
    hasRqe: true,
  },

  especialidadesLabel: 'Especialidades Médicas (Clínicas e Cirúrgicas)',
  especialidades: [
    { key: 'clinicaGeral', label: 'Clínica Médica / Medicina de Família', description: 'Atendimento ambulatorial clínico geral' },
    { key: 'cirurgiaGeral', label: 'Cirurgia Geral', description: 'Cirurgia geral e videolaparoscopia' },
    { key: 'ginecologiaObstetricia', label: 'Ginecologia e Obstetrícia', description: 'Consultório, partos e cirurgias ginecológicas' },
    { key: 'pediatria', label: 'Pediatria e Puericultura', description: 'Saúde infantil, neonatal e hebiatria' },
    { key: 'anestesiologia', label: 'Anestesiologia', description: 'Anestesia geral, regional e sedação consciente' },
    { key: 'dermatologia', label: 'Dermatologia & Procedimentos', description: 'Clínica dermatológica, biópsias e procedimentos estéticos' },
    { key: 'ortopediaTraumatologia', label: 'Ortopedia e Traumatologia', description: 'Traumatologia cirúrgica e reabilitação músculo-esquelética' },
    { key: 'oftalmologia', label: 'Oftalmologia', description: 'Clínica oftalmológica e cirurgias refrativas/catarata' },
    { key: 'cardiologia', label: 'Cardiologia & Hemodinâmica', description: 'Consultório, métodos gráficos e hemodinâmica intervencionista' },
    { key: 'cirurgiaPlastica', label: 'Cirurgia Plástica (Reparadora e Estética)', description: 'Procedimentos cirúrgicos plásticos estéticos e reparadores' },
    { key: 'neurologiaNeurocirurgia', label: 'Neurologia e Neurocirurgia', description: 'Tratamento clínico e cirúrgico do sistema nervoso central' },
    { key: 'psiquiatria', label: 'Psiquiatria & Saúde Mental', description: 'Psiquiatria clínica e psicoterapia médica' },
    { key: 'radiologiaDiagnostico', label: 'Radiologia e Diagnóstico por Imagem', description: 'Emissão de laudos de TC, RM, ultrassom e raio-x' },
    { key: 'urologia', label: 'Urologia', description: 'Procedimentos urológicos clínicos e cirúrgicos' },
    { key: 'otorrinolaringologia', label: 'Otorrinolaringologia', description: 'Clínica e cirurgias de ouvido, nariz e garganta' },
    { key: 'oncologia', label: 'Oncologia Clínica e Cirúrgica', description: 'Tratamento antineoplásico, quimioterapia e cirurgias oncológicas' },
    { key: 'medicinaIntensiva', label: 'Medicina Intensiva (UTI)', description: 'Manejo de pacientes críticos em unidades de terapia intensiva' },
    { key: 'endocrinologia', label: 'Endocrinologia e Metabologia', description: 'Doenças metabólicas, tireoide e hormonais' },
    { key: 'gastroenterologia', label: 'Gastroenterologia & Endoscopia', description: 'Aparelho digestivo, endoscopia e colonoscopia digestiva' },
    { key: 'outrosMed', label: 'Outras Especialidades Médicas', description: 'Demais especialidades registradas no CFM' },
  ],

  faturamentoLabel: 'Faturamento Bruto Anual de Honorários Médicos',
  hasFaturamento: true,
  hasPpe: true,
  requiresUnderwriting: true,

  questionarioRisco: [
    {
      id: 'propostaRecusada',
      question: 'Já teve proposta de seguro de RC Médico recusada, cancelada ou com recusa de renovação por qualquer seguradora?',
      detailKey: 'propostaDetalhe',
      detailLabel: 'Informe a seguradora, ano e justificativa da recusa',
      requiredOnAffirmative: true,
    },
    {
      id: 'processoConselho',
      question: 'Já foi intimado, respondeu ou responde a sindicância ou Processo Ético-Profissional (PEP) perante o CRM ou CFM?',
      detailKey: 'processoConselhoDetalhe',
      detailLabel: 'Informe o número do processo ético no CRM, UF, objeto da queixa e situação atual',
      requiredOnAffirmative: true,
    },
    {
      id: 'reclamacaoErroMedico',
      question: 'Já sofreu reclamação formal, processo cível de indenização ou inquérito/processo criminal decorrente de suposto erro médico ou conduta profissional nos últimos 5 anos?',
      detailKey: 'reclamacaoErroMedicoDetalhe',
      detailLabel: 'Descreva a ocorrência, dados da ação judicial, valores pleiteados e fase processual',
      requiredOnAffirmative: true,
    },
    {
      id: 'complicacoesCirurgicas',
      question: 'Nos últimos 3 anos, vivenciou evento adverso grave em seus procedimentos, como óbito perioperatório, infecção cirúrgica de alta complexidade ou retenção de corpo estranho?',
      detailKey: 'complicacoesCirurgicasDetalhe',
      detailLabel: 'Descreva o procedimento realizado, complicação ocorrida e desfecho clínico do paciente',
      requiredOnAffirmative: true,
    },
    {
      id: 'fatoPotencial',
      question: 'Tem ciência de qualquer notificação extrajudicial, reclamação em ouvidoria hospitalar ou insatisfação manifesta de paciente que possa originar processo indenizatório?',
      detailKey: 'fatoPotencialDetalhe',
      detailLabel: 'Detalhe as circunstâncias do caso, paciente envolvido e motivos da insatisfação',
      requiredOnAffirmative: true,
    },
    {
      id: 'pagamentoIndenizacao',
      question: 'Já realizou algum pagamento particular de indenização ou acordo extrajudicial direto com paciente por alegado erro médico nos últimos 5 anos?',
      detailKey: 'pagamentoIndenizacaoDetalhe',
      detailLabel: 'Informe valores pagos, termos do acordo e procedimento envolvido',
      requiredOnAffirmative: true,
    },
  ],

  planos: [
    {
      tipoDePlano: '200k',
      nomeExibido: 'Plano 200 Mil',
      cobertura: 'R$ 200.000,00',
      franquia: 'R$ 2.000,00',
      ordem: 1,
      parcela: 'R$ 1.850,00',
      parcela2X: 'R$ 925,00',
      parcela3X: 'R$ 616,67',
      parcela4X: 'R$ 462,50',
      parcela5X: 'R$ 370,00',
      parcela6X: 'R$ 308,33',
      valorPagoKovr: 1200,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '500k',
      nomeExibido: 'Plano 500 Mil',
      cobertura: 'R$ 500.000,00',
      franquia: 'R$ 5.000,00',
      ordem: 2,
      parcela: 'R$ 3.450,00',
      parcela2X: 'R$ 1.725,00',
      parcela3X: 'R$ 1.150,00',
      parcela4X: 'R$ 862,50',
      parcela5X: 'R$ 690,00',
      parcela6X: 'R$ 575,00',
      valorPagoKovr: 2200,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '1M',
      nomeExibido: 'Plano 1 Milhão',
      cobertura: 'R$ 1.000.000,00',
      franquia: 'R$ 10.000,00',
      ordem: 3,
      parcela: 'R$ 5.800,00',
      parcela2X: 'R$ 2.900,00',
      parcela3X: 'R$ 1.933,33',
      parcela4X: 'R$ 1.450,00',
      parcela5X: 'R$ 1.160,00',
      parcela6X: 'R$ 966,67',
      valorPagoKovr: 3700,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '2M',
      nomeExibido: 'Plano 2 Milhões',
      cobertura: 'R$ 2.000.000,00',
      franquia: 'R$ 15.000,00',
      ordem: 4,
      parcela: 'R$ 9.600,00',
      parcela2X: 'R$ 4.800,00',
      parcela3X: 'R$ 3.200,00',
      parcela4X: 'R$ 2.400,00',
      parcela5X: 'R$ 1.920,00',
      parcela6X: 'R$ 1.600,00',
      valorPagoKovr: 6100,
      maxParcelas: 6,
    },
  ],

  templateZapSignKey: 'rc_medicos_contrato_v1',
};
