import { RamoConfig } from '../types';

/**
 * Configuração declarativa do Seguro de Responsabilidade Civil Profissional para
 * Cirurgiões-Dentistas e Clínicas Odontológicas.
 */
export const rcOdontoConfig: RamoConfig = {
  ramoId: 'rc-odonto',
  name: 'RC Cirurgiões-Dentistas & Clínicas Odontológicas',
  shortName: 'RC Odontologia',
  category: 'responsabilidade_civil',
  flowKeys: ['rc_odonto_v1'],
  pricingStrategy: 'rc_odonto_planos_v1',
  policyPrefix: 'DL-RC-ODO',
  targetAudience: 'Cirurgiões-dentistas autônomos, consultórios e clínicas odontológicas com CRO ativo.',

  registroProfissional: {
    key: 'cro',
    label: 'Inscrição CRO',
    placeholder: 'Ex: 12345',
    ufKey: 'croUf',
    required: true,
    hasRqe: false,
  },

  especialidadesLabel: 'Especialidades Odontológicas',
  especialidades: [
    { key: 'implantodontia', label: 'Implantodontia', description: 'Cirurgia de implantes dentários e enxertos ósseos' },
    { key: 'harmonizacaoOrofacial', label: 'Harmonização Orofacial (HOF)', description: 'Toxina botulínica, preenchedores e fios faciais' },
    { key: 'ortodontia', label: 'Ortodontia & Ortopedia Facial', description: 'Aparelhos ortodônticos fixos, alinhadores e correções funcionais' },
    { key: 'endodontia', label: 'Endodontia', description: 'Tratamento de canais radiculares e cirurgias parendodônticas' },
    { key: 'periodontia', label: 'Periodontia', description: 'Tratamento gengival, cirurgias plásticas e regenerativas periodontais' },
    { key: 'cirurgiaBucomaxilofacial', label: 'Cirurgia e Traumatologia Bucomaxilofacial', description: 'Cirurgias ortognáticas, dentes inclusos e traumas em ambiente ambulatorial/hospitalar' },
    { key: 'clinicaGeral', label: 'Clínica Geral & Dentística Restauradora', description: 'Restaurações, facetas, clareamento e profilaxia' },
    { key: 'proteseDentaria', label: 'Prótese Dentária', description: 'Próteses fixas, removíveis, sobre implantes e reabilitação oral' },
    { key: 'odontopediatria', label: 'Odontopediatria', description: 'Atendimento odontológico preventivo e curativo em crianças' },
    { key: 'outrosOdonto', label: 'Outras Atuações Odontológicas', description: 'Demais especialidades registradas no CFO' },
  ],

  faturamentoLabel: 'Faturamento Bruto Anual da Atividade Odontológica',
  hasFaturamento: true,
  hasPpe: true,
  requiresUnderwriting: true,

  questionarioRisco: [
    {
      id: 'propostaRecusada',
      question: 'Já teve proposta de seguro odontológico recusada, cancelada ou sofrido agravo de taxa/franquia?',
      detailKey: 'propostaDetalhe',
      detailLabel: 'Informe a seguradora, época e motivo da recusa',
      requiredOnAffirmative: true,
    },
    {
      id: 'processoCro',
      question: 'Responde ou já respondeu a processo ético ou disciplinar perante o Conselho Regional de Odontologia (CRO) ou CFO?',
      detailKey: 'processoCroDetalhe',
      detailLabel: 'Informe a seccional do CRO, número do processo e status atual',
      requiredOnAffirmative: true,
    },
    {
      id: 'reclamacaoOdonto',
      question: 'Já recebeu notificação no Procon, processo cível de reparação de danos ou queixa por insatisfação com tratamentos (implantes, HOF, próteses)?',
      detailKey: 'reclamacaoOdontoDetalhe',
      detailLabel: 'Descreva os fatos alegados, valores cobrados e desfecho ou fase do processo',
      requiredOnAffirmative: true,
    },
    {
      id: 'complicacaoInvasiva',
      question: 'Vivenciou alguma intercorrência grave em procedimentos invasivos, como necrose tecidual ou oclusão vascular em HOF, lesão de nervo ou hospitalização de paciente?',
      detailKey: 'complicacaoInvasivaDetalhe',
      detailLabel: 'Descreva a intercorrência técnica, intervenções de emergência e quadro final do paciente',
      requiredOnAffirmative: true,
    },
    {
      id: 'fatoPendente',
      question: 'Tem ciência de qualquer paciente insatisfeito com risco iminente de litígio judicial ou reclamação formal pendente?',
      detailKey: 'fatoPendenteDetalhe',
      detailLabel: 'Descreva o procedimento realizado e as manifestações de insatisfação do paciente',
      requiredOnAffirmative: true,
    },
    {
      id: 'acordoIndenizatorio',
      question: 'Já efetuou devolução de valores, acordos indenizatórios extrajudiciais ou custeou retrabalhos com terceiros nos últimos 5 anos?',
      detailKey: 'acordoIndenizatorioDetalhe',
      detailLabel: 'Informe os valores despendidos e condições pactuadas',
      requiredOnAffirmative: true,
    },
  ],

  planos: [
    {
      tipoDePlano: '100k',
      nomeExibido: 'Plano 100 Mil',
      cobertura: 'R$ 100.000,00',
      franquia: 'R$ 1.000,00',
      ordem: 1,
      parcela: 'R$ 950,00',
      parcela2X: 'R$ 475,00',
      parcela3X: 'R$ 316,67',
      parcela4X: 'R$ 237,50',
      parcela5X: 'R$ 190,00',
      parcela6X: 'R$ 158,33',
      valorPagoKovr: 600,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '200k',
      nomeExibido: 'Plano 200 Mil',
      cobertura: 'R$ 200.000,00',
      franquia: 'R$ 2.000,00',
      ordem: 2,
      parcela: 'R$ 1.550,00',
      parcela2X: 'R$ 775,00',
      parcela3X: 'R$ 516,67',
      parcela4X: 'R$ 387,50',
      parcela5X: 'R$ 310,00',
      parcela6X: 'R$ 258,33',
      valorPagoKovr: 1000,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '500k',
      nomeExibido: 'Plano 500 Mil',
      cobertura: 'R$ 500.000,00',
      franquia: 'R$ 4.000,00',
      ordem: 3,
      parcela: 'R$ 2.900,00',
      parcela2X: 'R$ 1.450,00',
      parcela3X: 'R$ 966,67',
      parcela4X: 'R$ 725,00',
      parcela5X: 'R$ 580,00',
      parcela6X: 'R$ 483,33',
      valorPagoKovr: 1900,
      maxParcelas: 6,
    },
    {
      tipoDePlano: '1M',
      nomeExibido: 'Plano 1 Milhão',
      cobertura: 'R$ 1.000.000,00',
      franquia: 'R$ 8.000,00',
      ordem: 4,
      parcela: 'R$ 4.800,00',
      parcela2X: 'R$ 2.400,00',
      parcela3X: 'R$ 1.600,00',
      parcela4X: 'R$ 1.200,00',
      parcela5X: 'R$ 960,00',
      parcela6X: 'R$ 800,00',
      valorPagoKovr: 3100,
      maxParcelas: 6,
    },
  ],

  templateZapSignKey: 'rc_odonto_contrato_v1',
};
